# Copyright 2026 Florent Carli
# SPDX-License-Identifier: Apache-2.0

[workspace]
members = ["core"]

[workspace.package]
version = "0.6.0"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/insatomcat/open61850"

[package]
name = "open61850-rt"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Real-time Sampled Values engine of open61850"
repository.workspace = true
publish = false

[lib]
name = "open61850_rt"
crate-type = ["cdylib"]

[dependencies]
libc = "0.2"
open61850-core = { path = "core" }
pyo3 = { version = "0.25", features = ["extension-module", "abi3-py310"] }

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
