/* Copyright 2026 Florent Carli
 * SPDX-License-Identifier: Apache-2.0 */

#ifndef OPEN61850_H
#define OPEN61850_H

/* Generated by cbindgen from native/capi/src/lib.rs: do not edit. */

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

/**
 * Success.
 */
#define O61850_OK 0

/**
 * A required pointer is NULL.
 */
#define O61850_ERR_NULL -1

/**
 * The frame carries another EtherType, or is too short to have one.
 */
#define O61850_ERR_ETHERTYPE -2

/**
 * The APPID header is truncated, or its Length is inconsistent.
 */
#define O61850_ERR_HEADER -3

/**
 * Broken BER: a tag, a length, or a TLV running past its parent.
 */
#define O61850_ERR_BER -4

/**
 * A PDU field is missing, of the wrong size, or has an unexpected tag.
 */
#define O61850_ERR_FIELD -5

/**
 * noASDU does not match the ASDUs present.
 */
#define O61850_ERR_COUNT -6

/**
 * A GOOSE header counter is above 64 bits.
 */
#define O61850_ERR_TOO_LARGE -7

/**
 * An output buffer or array is too small; the size needed is returned.
 */
#define O61850_ERR_BUFFER -8

/**
 * allData values to encode are invalid: unknown kind, NULL octets with a
 * non-zero length, a structure lacking members, nesting deeper than 32,
 * a bit string with more than 7 unused bits.
 */
#define O61850_ERR_DATA -9

/**
 * Frame parameters out of range: VLAN id above 4095, priority above 7,
 * APDU above 65527 octets.
 */
#define O61850_ERR_FRAME -10

/**
 * A sample buffer whose length is not a multiple of 8.
 */
#define O61850_ERR_SAMPLES -11

/**
 * A bug in open61850 (a Rust panic, caught).
 */
#define O61850_ERR_INTERNAL -12

#define O61850_DATA_BOOLEAN 1

#define O61850_DATA_INTEGER 2

#define O61850_DATA_UNSIGNED 3

#define O61850_DATA_FLOAT32 4

#define O61850_DATA_FLOAT64 5

#define O61850_DATA_BIT_STRING 6

#define O61850_DATA_OCTET_STRING 7

#define O61850_DATA_VISIBLE_STRING 8

#define O61850_DATA_MMS_STRING 9

#define O61850_DATA_UTC_TIME 10

#define O61850_DATA_BINARY_TIME 11

#define O61850_DATA_STRUCTURE 12

#define O61850_DATA_ARRAY 13

#define O61850_DATA_RAW 14

/**
 * Ethernet and APPID headers of a received frame.
 */
typedef struct {
  uint8_t dst_mac[6];
  uint8_t src_mac[6];
  bool has_vlan;
  uint16_t vlan_id;
  uint8_t vlan_priority;
  uint16_t app_id;
  uint16_t reserved1;
  uint16_t reserved2;
} o61850_frame_info;

/**
 * Octets of a string or a buffer. In decoded values, `ptr` points into
 * the caller's frame and is NULL only for an absent optional field.
 */
typedef struct {
  const uint8_t *ptr;
  size_t len;
} o61850_bytes;

/**
 * MMS UtcTime: seconds since the UNIX epoch, fraction of second in 2^-24
 * units (24 bits), TimeQuality octet.
 */
typedef struct {
  uint32_t seconds;
  uint32_t fraction;
  uint8_t quality;
} o61850_utc_time;

/**
 * One Sampled Values ASDU (IEC 61850-9-2, IEC 61869-9).
 */
typedef struct {
  o61850_bytes sv_id;
  /**
   * `ptr` NULL when absent.
   */
  o61850_bytes dat_set;
  uint16_t smp_cnt;
  uint32_t conf_rev;
  bool has_refr_tm;
  o61850_utc_time refr_tm;
  uint8_t smp_synch;
  bool has_smp_rate;
  uint16_t smp_rate;
  /**
   * The seqData octets; `o61850_sv_int32_samples` splits the 9-2LE layout.
   */
  o61850_bytes sample;
  bool has_smp_mod;
  uint16_t smp_mod;
  /**
   * `ptr` NULL when absent; 8 octets in a conformant stream.
   */
  o61850_bytes gm_identity;
} o61850_sv_asdu;

/**
 * Bits packed MSB first; `unused` trailing bits of the last octet (0..7).
 */
typedef struct {
  o61850_bytes bits;
  uint8_t unused;
} o61850_bit_string;

/**
 * Any tag (the integer of its identifier octets) with its content.
 */
typedef struct {
  uint32_t tag;
  o61850_bytes value;
} o61850_raw;

/**
 * The value of an `o61850_data`, selected by its kind.
 */
typedef union {
  /**
   * BOOLEAN: 0 is FALSE, anything else TRUE.
   */
  uint8_t boolean;
  int64_t int64;
  uint64_t uint64;
  float float32;
  double float64;
  o61850_bit_string bit_string;
  /**
   * OCTET_STRING, VISIBLE_STRING (ASCII), MMS_STRING (UTF-8).
   */
  o61850_bytes octets;
  o61850_utc_time utc_time;
  /**
   * Milliseconds since midnight (4 octets), days since 1984-01-01 (2).
   */
  uint8_t binary_time[6];
  /**
   * STRUCTURE, ARRAY: number of members, which follow in the array.
   */
  size_t members;
  o61850_raw raw;
} o61850_data_value;

/**
 * One MMS Data value. A sequence of values is an array in preorder: a
 * STRUCTURE or an ARRAY of n members is followed by its n members, each
 * followed by its own. `kind` is one of `O61850_DATA_*` (0 is invalid).
 */
typedef struct {
  uint32_t kind;
  o61850_data_value value;
} o61850_data;

/**
 * A GOOSE message to encode. A string with `len` 0 may have a NULL `ptr`;
 * `go_id` is left out when its `ptr` is NULL. `all_data` holds
 * `all_data_len` values in preorder; with none, allData is written empty.
 */
typedef struct {
  o61850_bytes gocb_ref;
  uint32_t time_allowed_to_live;
  o61850_bytes dat_set;
  o61850_bytes go_id;
  o61850_utc_time t;
  uint32_t st_num;
  uint32_t sq_num;
  bool simulation;
  uint32_t conf_rev;
  bool nds_com;
  uint32_t num_dat_set_entries;
  const o61850_data *all_data;
  size_t all_data_len;
} o61850_goose_pdu;

/**
 * Where a frame to send goes.
 */
typedef struct {
  uint8_t dst_mac[6];
  uint8_t src_mac[6];
  uint16_t app_id;
  bool has_vlan;
  uint16_t vlan_id;
  uint8_t vlan_priority;
} o61850_address;

/**
 * A received GOOSE message. Counters are INT32U, read up to 64 bits.
 * `entries` counts the top-level values of allData, whose octets
 * `o61850_goose_values` reads.
 */
typedef struct {
  o61850_bytes gocb_ref;
  uint64_t time_allowed_to_live;
  o61850_bytes dat_set;
  /**
   * `ptr` NULL when absent.
   */
  o61850_bytes go_id;
  o61850_utc_time t;
  uint64_t st_num;
  uint64_t sq_num;
  bool simulation;
  uint64_t conf_rev;
  bool nds_com;
  uint64_t num_dat_set_entries;
  size_t entries;
  o61850_bytes all_data;
} o61850_goose_received;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * The version of open61850, as a static NUL-terminated string.
 */
const char *o61850_version(void);

/**
 * A static NUL-terminated description of a return code.
 */
const char *o61850_strerror(int32_t code);

/**
 * Decode a Sampled Values Ethernet frame (destination MAC first, with or
 * without one 802.1Q tag): every ASDU and every field, checked as
 * open61850's Python decoder checks them.
 *
 * `info` (headers) and `security` (`ptr` NULL when absent) may be NULL.
 * The first `capacity` ASDUs go to `asdus`, and `count` (may be NULL)
 * receives the number of ASDUs; `O61850_ERR_BUFFER` when it exceeds
 * `capacity`. For a refused frame, `info` holds the MAC addresses and the
 * VLAN tag when present, zeros otherwise, and `asdus` is unspecified.
 *
 * # Safety
 * `frame` valid for `len` octets; each non-NULL output pointer valid for a
 * write, `asdus` for `capacity` elements.
 */
int32_t o61850_sv_decode_frame(const uint8_t *frame,
                               size_t len,
                               o61850_frame_info *info,
                               o61850_bytes *security,
                               o61850_sv_asdu *asdus,
                               size_t capacity,
                               size_t *count);

/**
 * As `o61850_sv_decode_frame`, from the APPID field (the octets after the
 * EtherType). `info` receives the APPID header only.
 *
 * # Safety
 * As `o61850_sv_decode_frame`.
 */
int32_t o61850_sv_decode_payload(const uint8_t *payload,
                                 size_t len,
                                 o61850_frame_info *info,
                                 o61850_bytes *security,
                                 o61850_sv_asdu *asdus,
                                 size_t capacity,
                                 size_t *count);

/**
 * Split a 9-2LE / IEC 61869-9 sample buffer into INT32 values and 32-bit
 * qualities. The first `capacity` channels go to `values` and `qualities`
 * (either may be NULL); `count` (may be NULL) receives the number of
 * channels, `O61850_ERR_BUFFER` when it exceeds `capacity`.
 *
 * # Safety
 * `sample` valid for its length; `values` and `qualities` NULL or valid for
 * `capacity` elements.
 */
int32_t o61850_sv_int32_samples(o61850_bytes sample,
                                int32_t *values,
                                uint32_t *qualities,
                                size_t capacity,
                                size_t *count);

/**
 * Encode a complete GOOSE Ethernet frame (without FCS or padding) into
 * `out`, octet for octet as open61850's Python encoder writes it.
 * `out_len` (may be NULL) receives its length; with `O61850_ERR_BUFFER`,
 * the size needed (pass `out_size` 0 to ask for it). stNum, sqNum, t and
 * retransmission are the caller's.
 *
 * # Safety
 * `pdu` and `address` valid, with every octet pointer valid for its length
 * and `all_data` for `all_data_len` values; `out` valid for `out_size`
 * octets; `out_len` NULL or valid for a write.
 */
int32_t o61850_goose_encode_frame(const o61850_goose_pdu *pdu,
                                  const o61850_address *address,
                                  uint8_t *out,
                                  size_t out_size,
                                  size_t *out_len);

/**
 * As `o61850_goose_encode_frame`, for the IECGoosePdu alone (the APDU).
 *
 * # Safety
 * As `o61850_goose_encode_frame`.
 */
int32_t o61850_goose_encode_pdu(const o61850_goose_pdu *pdu,
                                uint8_t *out,
                                size_t out_size,
                                size_t *out_len);

/**
 * Decode a GOOSE Ethernet frame (destination MAC first, with or without
 * one 802.1Q tag): header fields and the TLV structure of allData at any
 * depth, checked as open61850's Python decoder checks them.
 *
 * `info` may be NULL; for a refused frame it holds the MAC addresses and
 * the VLAN tag when present (a receiver can recognise its own emission),
 * zeros otherwise. `message` is zeroed unless the frame is accepted.
 *
 * # Safety
 * `frame` valid for `len` octets; `info` NULL or valid for a write;
 * `message` valid for a write.
 */
int32_t o61850_goose_decode_frame(const uint8_t *frame,
                                  size_t len,
                                  o61850_frame_info *info,
                                  o61850_goose_received *message);

/**
 * As `o61850_goose_decode_frame`, from the APPID field (the octets after
 * the EtherType). `info` receives the APPID header only.
 *
 * # Safety
 * As `o61850_goose_decode_frame`.
 */
int32_t o61850_goose_decode_payload(const uint8_t *payload,
                                    size_t len,
                                    o61850_frame_info *info,
                                    o61850_goose_received *message);

/**
 * Read the allData values of a decoded message (its `all_data`) in
 * preorder. The first `capacity` values go to `values`; `count` (may be
 * NULL) receives the number of values, `O61850_ERR_BUFFER` when it exceeds
 * `capacity`. An INTEGER or unsigned beyond 64 bits comes out as RAW.
 *
 * `all_data` must come from an accepted message: other octets are read up
 * to their first malformed TLV.
 *
 * # Safety
 * `all_data` valid for its length; `values` NULL or valid for `capacity`
 * elements; `count` NULL or valid for a write.
 */
int32_t o61850_goose_values(o61850_bytes all_data,
                            o61850_data *values,
                            size_t capacity,
                            size_t *count);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* OPEN61850_H */
